version: 2
updates:
- package-ecosystem: npm
  directory: "/src/assetbundles/jasonfield"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: codejar
    versions:
    - 3.2.3
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.9
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.9
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.9
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
